<body>
    <div id="main-container">       
        <div class="container">
            <span class="top-label">
                <span class="label-txt">Proizvodi</span>
            </span>          
            <div class="content-area">   
                <div class="content drag-desired">
                    <input type='hidden' id='trenutnaStrana' />
                    <input type='hidden' id='prikazPoStrani' />
                    <div id='stranicenje'>
                        <?php
                        foreach ($this->proizvodi as $proizvod) {
                            echo '<div class="product"><img src="' . $proizvod->getSlikam() . '" alt="' . $proizvod->getNaziv() . '" width="128" height="128" class="pngfix" /></div>';
                        }
                        ?>
                    </div><div class="clear"></div><div id='strLinkovi'></div>
                    <div class="clear"></div>
                </div>                
            </div>         
            <div class="bottom-container-border">
            </div>
        </div>
        <div class="container">
            <span class="top-label">
                <span class="label-txt">Vaša e-korpa</span>
            </span>
            <div class="content-area">
                <div class="content drop-here">
                    <div id="cart-icon">
                        <img src="/img/Shoppingcart_128x128.png" alt="e-korpa" class="pngfix" width="128" height="128" />
                        <img src="/img/ajax_load_2.gif" alt="učitavanje.." id="ajax-loader" width="16" height="16" />
                    </div>
                    <form name="checkoutForm" method="post" action="Kupovina/pregled">
                        <div id="item-list">
                        </div>
                    </form>                
                    <div class="clear"></div>
                    <div id="total"></div>
                    <div class="clear"></div>
                    <a href="" onclick="document.forms.checkoutForm.submit();
                            return false;" class="button">Naručite</a>
                </div>
            </div>
            <div class="bottom-container-border">
            </div>
        </div>          
    </div>
</body>
</html>
