<?php $this->placeholder('korpa')->captureStart(); ?>

<link rel="stylesheet" type="text/css" href="/css/demo.css" />
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js"></script>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/jquery-ui.min.js"></script>
<script type="text/javascript" src="/simpletip/jquery.simpletip-1.3.1.pack.js"></script>
<script type="text/javascript" src="/js/script.js"></script>

<?php $this->placeholder('korpa')->captureEnd();
