<?php $this->placeholder('slajder')->captureStart(); ?>
<div id="templatemo_middle" class="carousel">
    <div class="panel">

        <div class="details_wrapper">

            <div class="details">

                <div class="detail">
                    <h2>Servis</h2>
                    <p>Na sve proizvode, dajemo garanciju 5 godina (osim SAT 03, gde je garantni rok 2 godine).
                        Telefon servisne službe: 063/437556, 022/315734 </p>
                </div><!-- /detail -->

                <div class="detail">
                    <h2>Referentna lista</h2>
                    <p>Poštujući privatnost naših korisnika, specifičnost upotrebne vrednosti proizvoda,
                        a na osnovu pismenih ugovora i usmenih dogovora, podatke o korisnicima držimo u tajnosti.</p>                   
                </div><!-- /detail -->

                <div class="detail">
                    <h2>O sefovima</h2>
                    <p>Sefovi marke SAFETRONICS su izrađeni na osnovu iskustava kriminologa, hotelijera, bankara...
                        Proizvođač sefova marke SAFETRONICS je firma Jozef Murgaš Elektronics iz Banske Bystrice - Republika Slovačka.</p>
                </div><!-- /detail -->

            </div><!-- /details -->

        </div><!-- /details_wrapper -->

        <div class="paging">
            <div id="numbers"></div>
            <a href="javascript:void(0);" class="previous" title="Previous" >Previous</a>
            <a href="javascript:void(0);" class="next" title="Next">Next</a>
        </div><!-- /paging -->

        <a href="javascript:void(0);" class="play" title="Turn on autoplay">Play</a>
        <a href="javascript:void(0);" class="pause" title="Turn off autoplay">Pause</a>

    </div><!-- /panel -->

    <div class="backgrounds">

        <div class="item item_1">
            <img src="/images/slider/02.jpg" alt="Slider 01" />
        </div><!-- /item -->

        <div class="item item_2">
            <img src="/images/slider/03.jpg" alt="Slider 02" />
        </div><!-- /item -->

        <div class="item item_3">
            <img src="/images/slider/01.jpg" alt="Slider 03" />
        </div><!-- /item -->

    </div><!-- /backgrounds -->
</div> <!-- END of templatemo_middle --> 
<?php $this->placeholder('slajder')->captureEnd(); ?>
