<div id="view-content">
    <div id="sadOautoru" style="width:680px; height:450px;">
        <div id="slikaAutora" style="width:300px; height:446px; float:left;"><img src="/images/jaMala.jpg" alt="moja slika" /></div>
        <div id="textOAutoru" style="width:350px; height:200px; float:right;">
            <h3 class="autor" style="margin-top:6px;">Milanko Topolski 1047/13</h3><br/>
            <p class="autorp">Rođen sam 20.12.1991. u Beogradu. Živim u Staroj Pazovi gde sam završio i osnovnu školu 2006 godine.
                Srednju elektrotehničku školu smer elektrotehničar računara završio sam u Inđiji 2010 godine.
                Trenutno pohađam specijalističke studije smer softversko inženjerstvo na visokoj ICT školi u Beogradu.</p>
        </div>
    </div>
</div>
